# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class FSpiderBriefInfo(scrapy.Item):
    matchid = scrapy.Field()
    status = scrapy.Field()
    game = scrapy.Field()
    turn = scrapy.Field()
    home_team = scrapy.Field()
    visit_team = scrapy.Field()
    gs = scrapy.Field()
    gd = scrapy.Field()
    gn = scrapy.Field()
    time = scrapy.Field()
    result = scrapy.Field()
    win_bet_return = scrapy.Field()
    draw_bet_return = scrapy.Field()
    lose_bet_return = scrapy.Field()


class FSpiderPredictInfo(scrapy.Item):
    fid = scrapy.Field()
    status = scrapy.Field()
    game = scrapy.Field()
    turn = scrapy.Field()
    home_team = scrapy.Field()
    visit_team = scrapy.Field()
    offset = scrapy.Field()
    time = scrapy.Field()


class FSpiderReferInfo(scrapy.Item):
    """docstring for FSpiderReferInfo"""

    fid = scrapy.Field()
    pos = scrapy.Field()
    name = scrapy.Field()
    date = scrapy.Field()
    host_team = scrapy.Field()
    visit_team = scrapy.Field()
    gs = scrapy.Field()
    gd = scrapy.Field()
    result = scrapy.Field()
    gn = scrapy.Field()


class FSpiderLotteryInfo(scrapy.Item):

    matchid = scrapy.Field()
    status = scrapy.Field()
    game = scrapy.Field()
    turn = scrapy.Field()
    home_team = scrapy.Field()
    visit_team = scrapy.Field()
    gs = scrapy.Field()
    gd = scrapy.Field()
    gn = scrapy.Field()
    time = scrapy.Field()
    result = scrapy.Field()
    win_bet_return = scrapy.Field()
    draw_bet_return = scrapy.Field()
    lose_bet_return = scrapy.Field()
    issue = scrapy.Field()

class FSpiderLotteryPredictInfo(scrapy.Item):

    matchid = scrapy.Field()
    status = scrapy.Field()
    game = scrapy.Field()
    turn = scrapy.Field()
    home_team = scrapy.Field()
    visit_team = scrapy.Field()
    time = scrapy.Field()
    win_bet_return = scrapy.Field()
    draw_bet_return = scrapy.Field()
    lose_bet_return = scrapy.Field()
    issue = scrapy.Field()

class FSpiderRecentFeatureInfo(scrapy.Item):
    matchid = scrapy.Field()

    h_abs_win = scrapy.Field()
    h_abs_draw = scrapy.Field()
    h_abs_lose = scrapy.Field()
    h_count = scrapy.Field()
    h_host_win = scrapy.Field()
    h_host_draw = scrapy.Field()
    h_host_lose = scrapy.Field()
    h_host_count = scrapy.Field()

    h_abs_gs = scrapy.Field()
    h_abs_gd = scrapy.Field()
    h_abs_g = scrapy.Field()
    h_abs_avg_gs = scrapy.Field()
    h_abs_avg_gd = scrapy.Field()
    h_abs_avg_g = scrapy.Field()

    h_host_gs = scrapy.Field()
    h_host_gd = scrapy.Field()
    h_host_g = scrapy.Field()
    # h_host_avg_gs = scrapy.Field()
    # h_host_avg_gd = scrapy.Field()
    # h_host_avg_g = scrapy.Field()

    h_0_1_gs = scrapy.Field()
    h_2_3_gs = scrapy.Field()
    h_ab_4_gs = scrapy.Field()
    h_0_gs = scrapy.Field()
    h_1_gs = scrapy.Field()
    h_2_gs = scrapy.Field()
    h_3_gs = scrapy.Field()
    h_4_gs = scrapy.Field()
    h_5_gs = scrapy.Field()
    h_6_gs = scrapy.Field()
    h_7_gs = scrapy.Field()

    h_0_1_gd = scrapy.Field()
    h_2_3_gd = scrapy.Field()
    h_ab_4_gd = scrapy.Field()
    h_0_gd = scrapy.Field()
    h_1_gd = scrapy.Field()
    h_2_gd = scrapy.Field()
    h_3_gd = scrapy.Field()
    h_4_gd = scrapy.Field()
    h_5_gd = scrapy.Field()
    h_6_gd = scrapy.Field()
    h_7_gd = scrapy.Field()

    v_abs_win = scrapy.Field()
    v_abs_draw = scrapy.Field()
    v_abs_lose = scrapy.Field()
    v_count = scrapy.Field()
    v_visit_win = scrapy.Field()
    v_visit_draw = scrapy.Field()
    v_visit_lose = scrapy.Field()
    v_visit_count = scrapy.Field()

    v_abs_gs = scrapy.Field()
    v_abs_gd = scrapy.Field()
    v_abs_g = scrapy.Field()
    v_abs_avg_gs = scrapy.Field()
    v_abs_avg_gd = scrapy.Field()
    v_abs_avg_g = scrapy.Field()

    v_visit_gs = scrapy.Field()
    v_visit_gd = scrapy.Field()
    v_visit_g = scrapy.Field()
    # v_visit_avg_gs = scrapy.Field()
    # v_visit_avg_gd = scrapy.Field()
    # v_visit_avg_g = scrapy.Field()

    v_0_1_gs = scrapy.Field()
    v_2_3_gs = scrapy.Field()
    v_ab_4_gs = scrapy.Field()
    v_0_gs = scrapy.Field()
    v_1_gs = scrapy.Field()
    v_2_gs = scrapy.Field()
    v_3_gs = scrapy.Field()
    v_4_gs = scrapy.Field()
    v_5_gs = scrapy.Field()
    v_6_gs = scrapy.Field()
    v_7_gs = scrapy.Field()

    v_0_1_gd = scrapy.Field()
    v_2_3_gd = scrapy.Field()
    v_ab_4_gd = scrapy.Field()
    v_0_gd = scrapy.Field()
    v_1_gd = scrapy.Field()
    v_2_gd = scrapy.Field()
    v_3_gd = scrapy.Field()
    v_4_gd = scrapy.Field()
    v_5_gd = scrapy.Field()
    v_6_gd = scrapy.Field()
    v_7_gd = scrapy.Field()


class FSpiderFeatureInfo(scrapy.Item):

    matchid = scrapy.Field()

    h_score = scrapy.Field()
    h_rank = scrapy.Field()

    h_perf_win = scrapy.Field()
    h_perf_draw = scrapy.Field()
    h_perf_lose = scrapy.Field()
    h_host_win = scrapy.Field()
    h_host_draw = scrapy.Field()
    h_host_lose = scrapy.Field()
    h_battle_with_front_10_win = scrapy.Field()
    h_battle_with_front_10_draw = scrapy.Field()
    h_battle_with_front_10_lose = scrapy.Field()
    h_battle_with_end_10_win = scrapy.Field()
    h_battle_with_end_10_draw = scrapy.Field()
    h_battle_with_end_10_lose = scrapy.Field()

    h_perf_gs = scrapy.Field()
    h_perf_gd = scrapy.Field()
    h_perf_avg_gs = scrapy.Field()
    h_perf_avg_gd = scrapy.Field()
    h_host_gs = scrapy.Field()
    h_host_gd = scrapy.Field()
    h_host_avg_gs = scrapy.Field()
    h_host_avg_gd = scrapy.Field()
    h_r3_gs = scrapy.Field()
    h_r3_gd = scrapy.Field()
    h_r3_avg_gs = scrapy.Field()
    h_r3_avg_gd = scrapy.Field()

    h_perf_bet_high = scrapy.Field()
    h_perf_bet_low = scrapy.Field()
    h_host_bet_high = scrapy.Field()
    h_host_bet_low = scrapy.Field()

    h_host_0_1_goal = scrapy.Field()
    h_host_2_3_goal = scrapy.Field()
    h_host_ab_4_goal = scrapy.Field()
    h_host_0_goal = scrapy.Field()
    h_host_1_goal = scrapy.Field()
    h_host_2_goal = scrapy.Field()
    h_host_3_goal = scrapy.Field()
    h_host_4_goal = scrapy.Field()
    h_host_5_goal = scrapy.Field()
    h_host_6_goal = scrapy.Field()
    h_host_7_goal = scrapy.Field()

    v_score = scrapy.Field()
    v_rank = scrapy.Field()

    v_perf_win = scrapy.Field()
    v_perf_draw = scrapy.Field()
    v_perf_lose = scrapy.Field()
    v_host_win = scrapy.Field()
    v_host_draw = scrapy.Field()
    v_host_lose = scrapy.Field()
    v_battle_with_front_10_win = scrapy.Field()
    v_battle_with_front_10_draw = scrapy.Field()
    v_battle_with_front_10_lose = scrapy.Field()
    v_battle_with_end_10_win = scrapy.Field()
    v_battle_with_end_10_draw = scrapy.Field()
    v_battle_with_end_10_lose = scrapy.Field()

    v_perf_gs = scrapy.Field()
    v_perf_gd = scrapy.Field()
    v_perf_avg_gs = scrapy.Field()
    v_perf_avg_gd = scrapy.Field()
    v_host_gs = scrapy.Field()
    v_host_gd = scrapy.Field()
    v_host_avg_gs = scrapy.Field()
    v_host_avg_gd = scrapy.Field()
    v_r3_gs = scrapy.Field()
    v_r3_gd = scrapy.Field()
    v_r3_avg_gs = scrapy.Field()
    v_r3_avg_gd = scrapy.Field()

    v_perf_bet_high = scrapy.Field()
    v_perf_bet_low = scrapy.Field()
    v_host_bet_high = scrapy.Field()
    v_host_bet_low = scrapy.Field()

    v_host_0_1_goal = scrapy.Field()
    v_host_2_3_goal = scrapy.Field()
    v_host_ab_4_goal = scrapy.Field()
    v_host_0_goal = scrapy.Field()
    v_host_1_goal = scrapy.Field()
    v_host_2_goal = scrapy.Field()
    v_host_3_goal = scrapy.Field()
    v_host_4_goal = scrapy.Field()
    v_host_5_goal = scrapy.Field()
    v_host_6_goal = scrapy.Field()
    v_host_7_goal = scrapy.Field()

class FSpiderOddInfo(scrapy.Item):
    matchid = scrapy.Field()
    avg_init_win_odd = scrapy.Field()
    avg_init_draw_odd = scrapy.Field()
    avg_init_lose_odd = scrapy.Field()
    avg_new_win_odd = scrapy.Field()
    avg_new_draw_odd = scrapy.Field()
    avg_new_lose_odd = scrapy.Field()
    avg_new_win_rate = scrapy.Field()
    avg_new_draw_rate = scrapy.Field()
    avg_new_lose_rate = scrapy.Field()
    avg_new_win_kelly = scrapy.Field()
    avg_new_draw_kelly = scrapy.Field()
    avg_new_lose_kelly = scrapy.Field()
    avg_pay_rate = scrapy.Field()

    max_init_win_odd = scrapy.Field()
    max_init_draw_odd = scrapy.Field()
    max_init_lose_odd = scrapy.Field()
    max_new_win_odd = scrapy.Field()
    max_new_draw_odd = scrapy.Field()
    max_new_lose_odd = scrapy.Field()
    max_new_win_rate = scrapy.Field()
    max_new_draw_rate = scrapy.Field()
    max_new_lose_rate = scrapy.Field()
    max_new_win_kelly = scrapy.Field()
    max_new_draw_kelly = scrapy.Field()
    max_new_lose_kelly = scrapy.Field()
    max_pay_rate = scrapy.Field()

    min_init_win_odd = scrapy.Field()
    min_init_draw_odd = scrapy.Field()
    min_init_lose_odd = scrapy.Field()
    min_new_win_odd = scrapy.Field()
    min_new_draw_odd = scrapy.Field()
    min_new_lose_odd = scrapy.Field()
    min_new_win_rate = scrapy.Field()
    min_new_draw_rate = scrapy.Field()
    min_new_lose_rate = scrapy.Field()
    min_new_win_kelly = scrapy.Field()
    min_new_draw_kelly = scrapy.Field()
    min_new_lose_kelly = scrapy.Field()
    min_pay_rate = scrapy.Field()

    std_win = scrapy.Field()
    std_draw = scrapy.Field()
    std_lose = scrapy.Field()

    dispersion_win = scrapy.Field()
    dispersion_draw = scrapy.Field()
    dispersion_lose = scrapy.Field()