scrapy crawl zgzcw_brief_info
scrapy crawl zgzcw_feature_info
scrapy crawl zgzcw_lottery_info
scrapy crawl zgzcw_lottery_feature_info
scrapy crawl zgzcw_lottery_predict_info
scrapy crawl zgzcw_lottery_predict_feature_info
