CREATE TABLE `breadt_football_game_list` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `fid` bigint(20) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT '',
  `game` varchar(100) DEFAULT '',
  `turn` varchar(100) DEFAULT '',
  `home_team` varchar(255) NOT NULL DEFAULT '',
  `visit_team` varchar(255) NOT NULL DEFAULT '',
  `gs` int(4) NOT NULL COMMENT '主队进球数',
  `gd` int(4) NOT NULL COMMENT '客队进球数',
  `gn` int(4) NOT NULL COMMENT '总进球数',
  `offset` varchar(20) DEFAULT NULL,
  `time` datetime NOT NULL,
  `result` int(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=79145 DEFAULT CHARSET=utf8;

CREATE TABLE `breadt_football_predict_game` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `fid` bigint(20) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT '',
  `game` varchar(100) DEFAULT '',
  `turn` varchar(100) DEFAULT '',
  `home_team` varchar(255) NOT NULL DEFAULT '',
  `visit_team` varchar(255) NOT NULL DEFAULT '',
  `offset` varchar(20) DEFAULT NULL,
  `time` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

CREATE TABLE `breadt_football_refer_games` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `fid` int(20) NOT NULL,
  `pos` varchar(20) NOT NULL DEFAULT '',
  `gd` int(4) NOT NULL,
  `gs` int(4) NOT NULL,
  `gn` int(4) NOT NULL,
  `result` int(4) NOT NULL,
  `home_team` varchar(255) NOT NULL DEFAULT '',
  `visit_team` varchar(255) NOT NULL DEFAULT '',
  `name` varchar(200) DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3521117 DEFAULT CHARSET=utf8;

CREATE TABLE `breadt_football_feature_info` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `matchid` bigint(20) DEFAULT NULL,
  `h_score` varchar(100) DEFAULT NULL,
  `h_rank` varchar(100) DEFAULT NULL,
  `h_perf_win` varchar(20) DEFAULT NULL,
  `h_perf_draw` varchar(20) DEFAULT NULL,
  `h_perf_lose` varchar(20) DEFAULT NULL,
  `h_host_win` varchar(20) DEFAULT NULL,
  `h_host_draw` varchar(20) DEFAULT NULL,
  `h_host_lose` varchar(20) DEFAULT NULL,
  `h_battle_with_front_10_win` varchar(20) DEFAULT NULL,
  `h_battle_with_front_10_draw` varchar(20) DEFAULT NULL,
  `h_battle_with_front_10_lose` varchar(20) DEFAULT NULL,
  `h_battle_with_end_10_win` varchar(20) DEFAULT NULL,
  `h_battle_with_end_10_draw` varchar(20) DEFAULT NULL,
  `h_battle_with_end_10_lose` varchar(20) DEFAULT NULL,
  `h_perf_gs` int(8) DEFAULT NULL,
  `h_perf_gd` int(8) DEFAULT NULL,
  `h_perf_avg_gs` float DEFAULT NULL,
  `h_perf_avg_gd` float DEFAULT NULL,
  `h_host_gs` int(8) DEFAULT NULL,
  `h_host_gd` int(8) DEFAULT NULL,
  `h_host_avg_gs` float DEFAULT NULL,
  `h_host_avg_gd` float DEFAULT NULL,
  `h_r3_gs` int(8) DEFAULT NULL,
  `h_r3_gd` int(8) DEFAULT NULL,
  `h_r3_avg_gs` float DEFAULT NULL,
  `h_r3_avg_gd` float DEFAULT NULL,
  `h_perf_bet_high` int(8) DEFAULT NULL,
  `h_perf_bet_low` int(8) DEFAULT NULL,
  `h_host_bet_high` int(8) DEFAULT NULL,
  `h_host_bet_low` int(8) DEFAULT NULL,
  `h_host_0_1_goal` int(8) DEFAULT NULL,
  `h_host_2_3_goal` int(8) DEFAULT NULL,
  `h_host_ab_4_goal` int(8) DEFAULT NULL,
  `h_host_0_goal` int(8) DEFAULT NULL,
  `h_host_1_goal` int(8) DEFAULT NULL,
  `h_host_2_goal` int(8) DEFAULT NULL,
  `h_host_3_goal` int(8) DEFAULT NULL,
  `h_host_4_goal` int(8) DEFAULT NULL,
  `h_host_5_goal` int(8) DEFAULT NULL,
  `h_host_6_goal` int(8) DEFAULT NULL,
  `h_host_7_goal` int(8) DEFAULT NULL,
  `v_score` varchar(100) DEFAULT NULL,
  `v_rank` varchar(100) DEFAULT NULL,
  `v_perf_win` varchar(20) DEFAULT NULL,
  `v_perf_draw` varchar(20) DEFAULT NULL,
  `v_perf_lose` varchar(20) DEFAULT NULL,
  `v_host_win` varchar(20) DEFAULT NULL,
  `v_host_draw` varchar(20) DEFAULT NULL,
  `v_host_lose` varchar(20) DEFAULT NULL,
  `v_battle_with_front_10_win` varchar(20) DEFAULT NULL,
  `v_battle_with_front_10_draw` varchar(20) DEFAULT NULL,
  `v_battle_with_front_10_lose` varchar(20) DEFAULT NULL,
  `v_battle_with_end_10_win` varchar(20) DEFAULT NULL,
  `v_battle_with_end_10_draw` varchar(20) DEFAULT NULL,
  `v_battle_with_end_10_lose` varchar(20) DEFAULT NULL,
  `v_perf_gs` int(8) DEFAULT NULL,
  `v_perf_gd` int(8) DEFAULT NULL,
  `v_perf_avg_gs` float DEFAULT NULL,
  `v_perf_avg_gd` float DEFAULT NULL,
  `v_host_gs` int(8) DEFAULT NULL,
  `v_host_gd` int(8) DEFAULT NULL,
  `v_host_avg_gs` float DEFAULT NULL,
  `v_host_avg_gd` float DEFAULT NULL,
  `v_r3_gs` int(8) DEFAULT NULL,
  `v_r3_gd` int(8) DEFAULT NULL,
  `v_r3_avg_gs` float DEFAULT NULL,
  `v_r3_avg_gd` float DEFAULT NULL,
  `v_perf_bet_high` int(8) DEFAULT NULL,
  `v_perf_bet_low` int(8) DEFAULT NULL,
  `v_host_bet_high` int(8) DEFAULT NULL,
  `v_host_bet_low` int(8) DEFAULT NULL,
  `v_host_0_1_goal` int(8) DEFAULT NULL,
  `v_host_2_3_goal` int(8) DEFAULT NULL,
  `v_host_ab_4_goal` int(8) DEFAULT NULL,
  `v_host_0_goal` int(8) DEFAULT NULL,
  `v_host_1_goal` int(8) DEFAULT NULL,
  `v_host_2_goal` int(8) DEFAULT NULL,
  `v_host_3_goal` int(8) DEFAULT NULL,
  `v_host_4_goal` int(8) DEFAULT NULL,
  `v_host_5_goal` int(8) DEFAULT NULL,
  `v_host_6_goal` int(8) DEFAULT NULL,
  `v_host_7_goal` int(8) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `breadt_lottery_info` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `game_start_date` text,
  `issue` int(20) NOT NULL,
  `matchid` int(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNI_MATCHID` (`matchid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;